# Generated by Django 5.2.4 on 2026-09-21 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_merge_20260921_1159'),
        ('core', '0004_payment'),
    ]

    operations = [
    ]
