# Generated by Django 5.2.4 on 2026-09-21 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_menuitem_image'),
        ('core', '0005_merge_0003_merge_20260921_1159_0004_payment'),
    ]

    operations = [
    ]
