# Generated by Django 5.2.4 on 2026-09-21 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_20260921_1352'),
        ('core', '0006_staffprofile_order_assignments'),
    ]

    operations = [
    ]
