import React from 'react';
import {Routes,Route,Link,Navigate,useLocation} from 'react-router-dom';
import Dashboard from './pages/Dashboard';import MenuItemsPage from './pages/MenuItemsPage';import AddMenuItem from './pages/AddMenuItem';import OrdersPage from './pages/OrdersPage';import CustomerMenu from './pages/CustomerMenu';import KitchenDisplay from './pages/KitchenDisplay';import WaiterBoard from './pages/WaiterBoard';import FloorPlan from './pages/FloorPlan';import Reservations from './pages/Reservations';import POS from './pages/POS';import RestaurantSetup from './pages/RestaurantSetup';import Staff from './pages/Staff';import Login from './pages/Login';import{useAuth}from'./context/AuthContext';
import'bootstrap/dist/css/bootstrap.min.css';import'bootstrap-icons/font/bootstrap-icons.css';import'./App.css';

const access={
 '/':['owner','manager'], '/menu-items':['owner','manager'], '/add-menu-item':['owner','manager'],
 '/pos':['owner','manager','cashier'], '/setup':['owner'], '/floor':['owner','manager','waiter','cashier'],
 '/reservations':['owner','manager','waiter','cashier'], '/orders':['owner','manager','waiter','cashier','kitchen'],
 '/staff':['owner','manager'], '/kitchen':['owner','manager','kitchen'], '/service':['owner','manager','waiter']
};
const roleHome={owner:'/',manager:'/',cashier:'/pos',waiter:'/service',kitchen:'/kitchen',storekeeper:'/'};
function Guard({path,children}){const{user,ready}=useAuth();const loc=useLocation();if(!ready)return <div className="p-5 text-center">Loading workspace…</div>;if(!user)return <Navigate to="/login" state={{from:loc.pathname}} replace/>;if(!(access[path]||[]).includes(user.role))return <Navigate to={roleHome[user.role]||'/login'} replace/>;return children}
function App(){const location=useLocation();const{user,logout}=useAuth();const customerExperience=location.pathname==='/menu';const authScreen=location.pathname==='/login';const links=[
 ['Menu Manager','/menu-items',['owner','manager']],['POS','/pos',['owner','manager','cashier']],['Floor','/floor',['owner','manager','waiter','cashier']],['Reservations','/reservations',['owner','manager','waiter','cashier']],['Orders','/orders',['owner','manager','waiter','cashier','kitchen']],['Staff','/staff',['owner','manager']],['Kitchen','/kitchen',['owner','manager','kitchen']],['Service','/service',['owner','manager','waiter']]
 ];
 return <div className="container-fluid p-0">{!customerExperience&&!authScreen&&user&&<><header className="bg-dark text-white py-3 px-4 shadow-sm d-flex justify-content-between align-items-center"><div><strong>Savour Restaurant OS</strong><small className="d-block text-white-50">{user.name} · {user.role}</small></div><button className="btn btn-outline-light btn-sm" onClick={logout}>Logout</button></header><nav className="navbar navbar-expand-md navbar-light bg-light px-3"><div className="container-fluid"><Link className="navbar-brand" to={roleHome[user.role]||'/'}><i className="bi bi-speedometer2 me-2"></i>Workspace</Link><div className="navbar-nav ms-auto">{links.filter(([, ,roles])=>roles.includes(user.role)).map(([label,path])=><Link className="nav-link" to={path} key={path}>{label}</Link>)}<Link className="nav-link" to="/menu">Customer Menu</Link></div></div></nav></>}<main className={customerExperience||authScreen?'':'px-4 py-3'}><Routes>
 <Route path="/login" element={<Login/>}/><Route path="/menu" element={<CustomerMenu/>}/>
 <Route path="/" element={<Guard path="/"><Dashboard/></Guard>}/><Route path="/menu-items" element={<Guard path="/menu-items"><MenuItemsPage/></Guard>}/><Route path="/add-menu-item" element={<Guard path="/add-menu-item"><AddMenuItem/></Guard>}/><Route path="/pos" element={<Guard path="/pos"><POS/></Guard>}/><Route path="/setup" element={<Guard path="/setup"><RestaurantSetup/></Guard>}/><Route path="/floor" element={<Guard path="/floor"><FloorPlan/></Guard>}/><Route path="/reservations" element={<Guard path="/reservations"><Reservations/></Guard>}/><Route path="/orders" element={<Guard path="/orders"><OrdersPage/></Guard>}/><Route path="/staff" element={<Guard path="/staff"><Staff/></Guard>}/><Route path="/kitchen" element={<Guard path="/kitchen"><KitchenDisplay/></Guard>}/><Route path="/service" element={<Guard path="/service"><WaiterBoard/></Guard>}/>
 </Routes></main></div>}
export default App;