import React,{useEffect,useState}from'react';import{api}from'../services/api';import'./CashierShift.css';

export default function CashierShift(){
 const[data,setData]=useState({shift:null,totals:{cash:0,card:0,mpesa:0}}),[history,setHistory]=useState([]),[opening,setOpening]=useState(''),[counted,setCounted]=useState(''),[message,setMessage]=useState('');
 const load=async()=>{try{const[c,h]=await Promise.all([api.get('cashier-shifts/current/'),api.get('cashier-shifts/')]);setData(c.data);setHistory(h.data)}catch(e){setMessage(e.response?.data?.detail||'Could not load shift.')}};
 useEffect(()=>{load()},[]);
 const open=async()=>{try{await api.post('cashier-shifts/open/',{opening_float:Number(opening||0)});setOpening('');setMessage('Shift opened. Payments will now be reconciled to this cashier.');load()}catch(e){setMessage(e.response?.data?.detail||e.response?.data?.opening_float||'Could not open shift.')}};
 const close=async()=>{if(!data.shift)return;try{const r=await api.post('cashier-shifts/'+data.shift.id+'/close/',{counted_cash:Number(counted)});setData(r.data);setCounted('');setMessage('Shift closed. Variance recorded.');load()}catch(e){setMessage(e.response?.data?.detail||e.response?.data?.counted_cash||'Could not close shift.')}};
 const s=data.shift,t=data.totals||{};const expected=Number(s?.opening_float||0)+Number(t.cash||0);
 return <main className="shift-shell"><header><div><span>Cash control</span><h1>Cashier shift</h1><p>Open the till, reconcile every payment method, count cash and close the day with a recorded variance.</p></div><div className={'shift-badge '+(s?'open':'closed')}>{s?'SHIFT OPEN':'NO OPEN SHIFT'}</div></header>
 {message&&<div className="shift-message">{message}</div>}
 {!s?<section className="open-shift"><div><small>Start of shift</small><h2>Open your till</h2><p>Enter the physical cash placed in the drawer before sales begin.</p></div><label>Opening float (KSh)<input type="number" min="0" value={opening} onChange={e=>setOpening(e.target.value)} placeholder="e.g. 5000"/></label><button onClick={open}>Open shift</button></section>:<>
 <section className="shift-kpis"><article><small>Opening float</small><strong>KSh {Number(s.opening_float).toLocaleString()}</strong></article><article><small>Cash sales</small><strong>KSh {Number(t.cash||0).toLocaleString()}</strong></article><article><small>M-Pesa</small><strong>KSh {Number(t.mpesa||0).toLocaleString()}</strong></article><article><small>Card</small><strong>KSh {Number(t.card||0).toLocaleString()}</strong></article></section>
 <section className="reconcile"><div><small>Expected drawer</small><h2>KSh {expected.toLocaleString()}</h2><p>Opening float + paid cash transactions since {new Date(s.opened_at).toLocaleString()}.</p></div><div className="close-form"><label>Counted physical cash<input type="number" min="0" value={counted} onChange={e=>setCounted(e.target.value)} placeholder="Count drawer"/></label><div className="variance-preview"><span>Current variance</span><strong>KSh {(Number(counted||0)-expected).toLocaleString()}</strong></div><button disabled={counted===''} onClick={close}>Close & reconcile shift</button></div></section></>}
 <section className="shift-history"><h2>Shift history</h2><div className="shift-head"><span>Cashier</span><span>Opened</span><span>Closed</span><span>Expected cash</span><span>Counted</span><span>Variance</span></div>{history.map(x=><div className="shift-row" key={x.id}><span>{x.cashier_name}</span><span>{new Date(x.opened_at).toLocaleString()}</span><span>{x.closed_at?new Date(x.closed_at).toLocaleString():'Open'}</span><strong>KSh {Number(x.expected_cash).toLocaleString()}</strong><strong>{x.counted_cash==null?'—':'KSh '+Number(x.counted_cash).toLocaleString()}</strong><strong className={Number(x.variance)===0?'ok':Number(x.variance)<0?'short':'over'}>KSh {Number(x.variance).toLocaleString()}</strong></div>)}</section>
 </main>
}