import React,{useCallback,useEffect,useState} from 'react';
import{api}from'../services/api';
import'./Reservations.css';
function Reservations(){
 const[rows,setRows]=useState([]);const[tables,setTables]=useState([]);const[show,setShow]=useState(false);
 const[form,setForm]=useState({customer_name:'',phone:'',party_size:2,reservation_at:'',table:'',notes:'',status:'confirmed'});
 const load=useCallback(()=>Promise.all([api.get('reservations/'),api.get('tables/')]).then(([r,t])=>{setRows(r.data);setTables(t.data)}),[]);
 useEffect(()=>{load()},[load]);
 const submit=async e=>{e.preventDefault();await api.post('reservations/',{...form,party_size:Number(form.party_size),table:form.table?Number(form.table):null});setShow(false);load()};
 const patch=async(r,status)=>{await api.patch('reservations/'+r.id+'/',{status});if(status==='seated'&&r.table)await api.patch('tables/'+r.table+'/',{status:'occupied'});load()};
 return <div className="res-shell"><header><div><span>Guest book</span><h1>Reservations</h1><p>Welcome guests before they even arrive.</p></div><button onClick={()=>setShow(true)}>+ New reservation</button></header><div className="res-list">{rows.map(r=><article key={r.id}><div className="datebox"><strong>{new Date(r.reservation_at).getDate()}</strong><span>{new Date(r.reservation_at).toLocaleString('en',{month:'short'})}</span></div><div className="guest"><h3>{r.customer_name}</h3><p>{r.party_size} guests · {new Date(r.reservation_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})} · {r.table_number?'Table '+r.table_number:'Table unassigned'}</p>{r.notes&&<small>{r.notes}</small>}</div><span className={'res-status '+r.status}>{r.status.replace('_',' ')}</span><div className="res-actions">{r.status==='confirmed'&&<button onClick={()=>patch(r,'seated')}>Seat guests</button>}<button className="ghost" onClick={()=>patch(r,'cancelled')}>•••</button></div></article>)}{!rows.length&&<div className="no-res">No reservations yet.</div>}</div>{show&&<div className="modal-bg" onClick={()=>setShow(false)}><form className="res-form" onSubmit={submit} onClick={e=>e.stopPropagation()}><button type="button" className="x" onClick={()=>setShow(false)}>×</button><span>New booking</span><h2>Save their table.</h2><input required placeholder="Guest name" onChange={e=>setForm({...form,customer_name:e.target.value})}/><input required placeholder="Phone number" onChange={e=>setForm({...form,phone:e.target.value})}/><input required type="number" min="1" value={form.party_size} onChange={e=>setForm({...form,party_size:e.target.value})}/><input required type="datetime-local" onChange={e=>setForm({...form,reservation_at:e.target.value})}/><select onChange={e=>setForm({...form,table:e.target.value})}><option value="">Assign later</option>{tables.filter(t=>t.active).map(t=><option value={t.id} key={t.id}>Table {t.number} · {t.seats} seats</option>)}</select><textarea placeholder="Birthday, accessibility, seating preference…" onChange={e=>setForm({...form,notes:e.target.value})}/><button className="save">Confirm reservation</button></form></div>}</div>
}
export default Reservations;