import React,{useEffect,useMemo,useState}from'react';import{api}from'../services/api';import'./Transactions.css';

export default function Transactions(){
 const[payments,setPayments]=useState([]),[search,setSearch]=useState(''),[method,setMethod]=useState('all'),[status,setStatus]=useState('all'),[date,setDate]=useState(''),[receipt,setReceipt]=useState(null),[error,setError]=useState('');
 const load=async()=>{try{const r=await api.get('payments/');setPayments(r.data)}catch{setError('Could not load transactions.')}};
 useEffect(()=>{load()},[]);
 const rows=useMemo(()=>payments.filter(p=>{
  const q=search.toLowerCase().trim();
  const hay=[p.reference,p.phone_number,p.order,p.order_table,p.cashier_name].join(' ').toLowerCase();
  const day=(p.paid_at||p.created_at||'').slice(0,10);
  return(!q||hay.includes(q))&&(method==='all'||p.method===method)&&(status==='all'||p.status===status)&&(!date||day===date)
 }),[payments,search,method,status,date]);
 const paid=rows.filter(p=>p.status==='paid');const total=paid.reduce((n,p)=>n+Number(p.amount),0);
 const openReceipt=async p=>{try{const r=await api.get('orders/'+p.order+'/receipt/');setReceipt(r.data)}catch{setError('Could not open receipt.')}};
 return <main className="tx-shell"><header><div><span>Finance desk</span><h1>Transactions & receipts</h1><p>Search payments, trace M-Pesa receipts and reprint settled bills.</p></div><div className="tx-total"><small>Filtered paid total</small><strong>KSh {total.toLocaleString()}</strong></div></header>
 <section className="tx-filters"><input placeholder="Search receipt, phone, order, table or cashier…" value={search} onChange={e=>setSearch(e.target.value)}/><select value={method} onChange={e=>setMethod(e.target.value)}><option value="all">All methods</option><option value="mpesa">M-Pesa</option><option value="cash">Cash</option><option value="card">Card</option></select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option><option value="paid">Paid</option><option value="pending">Pending</option><option value="failed">Failed</option><option value="refunded">Refunded</option></select><input type="date" value={date} onChange={e=>setDate(e.target.value)}/><button onClick={()=>{setSearch('');setMethod('all');setStatus('all');setDate('')}}>Clear</button></section>
 {error&&<div className="tx-error">{error}</div>}<section className="tx-table"><div className="tx-head"><span>Transaction</span><span>Order / Table</span><span>Method</span><span>Status</span><span>Amount</span><span></span></div>{rows.map(p=><div className="tx-row" key={p.id}><div><strong>{p.reference||'No reference'}</strong><small>{new Date(p.paid_at||p.created_at).toLocaleString()}</small></div><div><b>#{p.order}</b><small>{p.order_table?'Table '+p.order_table:'No table'}{p.cashier_name?' · '+p.cashier_name:''}</small></div><span>{p.method.toUpperCase()}</span><span className={'tx-status '+p.status}>{p.status}</span><strong>KSh {Number(p.amount).toLocaleString()}</strong><button onClick={()=>openReceipt(p)}>Receipt</button></div>)}{!rows.length&&<div className="tx-empty">No transactions match these filters.</div>}</section>
 {receipt&&<div className="receipt-modal" onClick={()=>setReceipt(null)}><article onClick={e=>e.stopPropagation()}><button className="close-receipt" onClick={()=>setReceipt(null)}>×</button><h2>SAVOUR</h2><p>Restaurant & Lounge</p><h3>Receipt {receipt.receipt_number}</h3>{receipt.order.details.map(i=><div className="receipt-line" key={i.id}><span>{i.quantity} × {i.menu_item_name}</span><b>KSh {Number(i.subtotal).toLocaleString()}</b></div>)}<hr/>{receipt.payments.filter(p=>p.status==='paid').map(p=><div className="receipt-line" key={p.id}><span>{p.method.toUpperCase()}{p.reference?' · '+p.reference:''}</span><b>KSh {Number(p.amount).toLocaleString()}</b></div>)}<div className="receipt-line receipt-total"><span>Total paid</span><b>KSh {Number(receipt.paid_total).toLocaleString()}</b></div><button className="print-btn" onClick={()=>window.print()}>Print receipt</button></article></div>}</main>
}